APIVersion: v1.10.2
name: web-scraping
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "8688"
router_https_port: "8643"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
hooks:
  post-import-db:
  - exec: drush config-set system.site name WebScraping
  - exec: drush cr
  post-start:
  - exec: drush site-install server -y --db-url=mysql://db:db@db/db --account-pass=admin
      --existing-config
  - exec: drush en server_migrate -y
  - exec: drush migrate:import --group=server
omit_containers: [dba, ddev-ssh-agent]
use_dns_when_possible: true
timezone: ""
